"""Each player's home state (where they went to high school, not where their college is), for the "State"
column next to Team on the Studies page. Same verification bar as the Hudl links: only added when a
source directly stated a hometown/high school location, never guessed from a school's general recruiting
region. Two-letter USPS code for a US state; a non-US hometown (e.g. Ontario, Canada) is spelled out
since there's no state code for it. Hand-fill the rest in the Studies page itself -- blank just means not
found yet."""

HOME_STATES = {
    "BRADEN AWLS": "OH",
    "ANTHONY TORRES": "IN",
    "MITCHEL COLLIER": "IN",
    "BLAKE BOSMA": "MI",
    "JYRIN JOHNSON": "LA",
    "BRIAN SHANE": "OH",
    "JACOB ORLANDO": "NY",
    "TJ BANKS": "PA",
    "RILEY TOLSMA": "MI",
    "CAIDEN WOULLARD": "OH",
    "JUDGE CULPEPPER": "FL",
    "BRYCE SHEPPERT": "OH",
    "NIK MCMILLAN": "NY",
    "NATHAN VOORHIS": "PA",
    "TY WISE": "IN",
    "MAXEN HOOK": "IN",
    "NOAH KIM": "VA",
    "CHIP TRAYANUM": "OH",
    "JORDAN OLADOKUN": "FL",
    "JALEN MCCLENDON": "FL",
    "JALEN HUSKEY": "MD",
    "KAY'RON LYNCH-ADAMS": "OH",
    "DONTAE MCMILLAN": "WA",
    "RAION STRADER": "PA",
    "DECORION TEMPLE": "MI",
    "JOSHUA LONG": "CA",
    "TANNER KOZIOL": "IL",
    "VICTOR SNOW": "NY",
    "PEYTON PRICE": "IN",
    "BILHAL KONE": "MN",
    "AVERY SMITH": "GA",
    "JORDAN KWIATKOWSKI": "MI",
    "AARON WOFFORD": "IL",
    "DARRIAN LEWIS": "OH",
    "ADAM TRICK": "OH",
    "BRYCE HOUSTON": "OH",
    "CHASE KLINE": "OH",
    "BRYAN MCCOY": "IL",
    "JOE SPARACIO": "FL",
    "KOBE STEWART": "AL",
    "BRADLEY WEAVER": "OH",
    "RODNEY MCGRAW": "IL",
    "CONNOR BAZELAK": "OH",
    "BEN FINLEY": "AZ",
    "HAROLD FANNIN JR.": "OH",
    "MASON WILLIAMS": "OH",
    "ADRIAN NORTON": "OH",
    "DEVIN GRANT": "NY",
    "GIDEON LAMPRON": "OH",
    "JACKSON KUWATCH": "OH",
    "JALEN THOMESON": "IN",
    "JOSEPH SIPP JR.": "FL",
    "SILAS WALTERS": "OH",
    "ANTHONY SIMPSON": "CT",
    "BROC LOWRY": "OH",
    "BRYCE LLEWELLYN": "IN",
    "CJ NUNNALLY": "GA",
    "CHARLES MCCARTHERENS": "GA",
    "COLE SNYDER": "NY",
    "DEQUAN FINN": "MI",
    "JASE BAUER": "IA",
    "KADIN SEMONZA": "CA",
    "KURTIS ROURKE": "Ontario, Canada",
    "MICHAEL HELDMAN": "MI",
    "NADAME TUCKER": "NY",
    "PARKER NAVARRO": "AZ",
    "TATE HALLOCK": "MI",
    "TUCKER GLEASON": "FL",
    "BRETT GABBERT": "MO",
    # Already surfaced earlier in this session's Hudl-link / stat-fix research -- reused here rather than
    # re-searched.
    "DONOVAN GREEN": "LA",
    "KAM PERRY": "GA",
    "KENNETH WOMACK": "MD",
    "KEYON MOZEE": "MO",
    "MJ CANNON": "IL",
    "MATT SALOPEK": "OH",
    "PAUL LEWIS III": "MD",
    "RASHAD AMOS": "GA",
    "TANK PEARSON": "MS",
    "AL-JAY HENDERSON": "NJ",
    "ANTHONY TYUS III": "MI",
    "CHASE HENDRICKS": "MO",
    "COLEMAN OWEN": "AZ",
    "ELI BLAKEY": "KY",
    "GAGE LARVADAIN": "LA",
    "JADEN NIXON": "TX",
    "JALEN BUCKLEY": "IL",
    "JERJUAN NEWTON": "FL",
    "JORDAN GANT": "FL",
    "JUNIOR VANDEROSS III": "FL",
    "KAL-EL PASCAL": "FL",
    "MARQUEZ COOPER": "MD",
    "MARSHAWN KNEELAND": "MI",
    "PENY BOONE": "MI",
    "QUINYON MITCHELL": "FL",
    "RED MURDOCK": "VA",
    "REGGIE VIRGIL": "FL",
    "SHAUN DOLAC": "NY",
    "SIDNEY HOUSTON": "IL",
    "SIEH BANGURA": "MD",
    "TERION STEWART": "OH",
    "JARVARIUS SIMS": "GA",
    "JOJO JOHNSON": "IN",
}
