"""Each player's home state (where they went to high school, not where their college is), for the "State"
column next to Team on the Studies page. Same verification bar as the Hudl links: only added when a
source directly stated a hometown/high school location, never guessed from a school's general recruiting
region. Two-letter USPS code for a US state; a non-US hometown (e.g. Ontario, Canada) is spelled out
since there's no state code for it. Hand-fill the rest in the Studies page itself -- blank just means not
found yet."""

HOME_STATES = {
    "BRADEN AWLS": "OH",
    "ANTHONY TORRES": "IN",
    "MITCHEL COLLIER": "IN",
    "BLAKE BOSMA": "MI",
    "JYRIN JOHNSON": "LA",
    "BRIAN SHANE": "OH",
    "JACOB ORLANDO": "NY",
    "TJ BANKS": "PA",
    "RILEY TOLSMA": "MI",
    "CAIDEN WOULLARD": "OH",
    "JUDGE CULPEPPER": "FL",
    "BRYCE SHEPPERT": "OH",
    "NIK MCMILLAN": "NY",
    "NATHAN VOORHIS": "PA",
    "TY WISE": "IN",
    "MAXEN HOOK": "IN",
    "NOAH KIM": "VA",
    "CHIP TRAYANUM": "OH",
    "JORDAN OLADOKUN": "FL",
    "JALEN MCCLENDON": "FL",
    "JALEN HUSKEY": "MD",
    "KAY'RON LYNCH-ADAMS": "OH",
    "DONTAE MCMILLAN": "WA",
    "RAION STRADER": "PA",
    "DECORION TEMPLE": "MI",
    "JOSHUA LONG": "CA",
    "TANNER KOZIOL": "IL",
    "VICTOR SNOW": "NY",
    "PEYTON PRICE": "IN",
    "BILHAL KONE": "MN",
    "AVERY SMITH": "GA",
    "JORDAN KWIATKOWSKI": "MI",
    "AARON WOFFORD": "IL",
    "DARRIAN LEWIS": "OH",
    "ADAM TRICK": "OH",
    "BRYCE HOUSTON": "OH",
    "CHASE KLINE": "OH",
    "BRYAN MCCOY": "IL",
    "JOE SPARACIO": "FL",
    "KOBE STEWART": "AL",
    "BRADLEY WEAVER": "OH",
    "RODNEY MCGRAW": "IL",
    "CONNOR BAZELAK": "OH",
    "BEN FINLEY": "AZ",
    "HAROLD FANNIN JR.": "OH",
    "MASON WILLIAMS": "OH",
}
