"""
One-off data pull for the Studies dashboard's first study: the top 5 most productive MAC players at each
position, for each of the 2023, 2024, 2025 and 2026 seasons -- kept as separate rankings (not combined
across years), so the study answers "who had the best year in the league at this position, in this
specific season" rather than a multi-year aggregate. 2026 is the current, in-progress season: its totals
are season-to-date, not final, and will keep growing as the season goes on. Not part of the regular
weekly refresh for 2023-2025 (those are frozen, hand-curated seasons) -- but 2026 IS now regenerated by
weekly-data-refresh.yml automatically (right after it refreshes real-stats.json), so the study keeps
itself current through the season with no manual reruns or hand-patched overrides needed. Can still be
run by hand too, any time:

    python3 studies/mac_best_by_position.py

2023-2025 come from the NCAA API's national leaderboards (ncaa_api.py, season override), which only carry
a player once they crack roughly the national top 100-150 in that category that season -- a genuinely
elite conference performer is covered, but a solid-but-not-nationally-ranked one may be missing (patched
by hand via STAT_OVERRIDES/TE_SUPPLEMENT/CB_SUPPLEMENT for those three frozen seasons).

2026 instead comes straight from frontend/src/data/real-stats.json -- the same file the Pre-Portal
Tracker itself reads, built weekly by build_data.py from ESPN's roster-level API. That file carries every
rostered MAC player's full stat line, not just whoever cracked a national leaderboard, so 2026 needs none
of the above hand-patching at all -- it was built for exactly this gap (see fetch_season_from_real_stats).

MAC membership was stable across 2023-2025 (Massachusetts already in since 2022). Northern Illinois left
for the Mountain West and Sacramento St. joined for 2026 -- MAC_TEAMS is season-aware specifically for
that swap (see mac_teams_for) for the 2023-2025 leaderboard path; the real-stats.json path for 2026
already tags Sacramento St.'s rows "MAC" itself, confirmed directly.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ncaa_api import build_division_rows
from studies._hudl_links import HUDL_LINKS, PFF_LINKS, TE_SUPPLEMENT, CB_SUPPLEMENT, QB_SUPPLEMENT, WR_SUPPLEMENT
from studies._stat_overrides import STAT_OVERRIDES
from studies._home_states import HOME_STATES

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT_PATH = os.path.join(REPO_ROOT, "frontend", "src", "data", "studies", "mac-best-by-position.json")
REAL_STATS_PATH = os.path.join(REPO_ROOT, "frontend", "src", "data", "real-stats.json")
# The only season that sources from real-stats.json instead of the NCAA leaderboard -- see fetch_season.
REAL_STATS_SEASON = "2026"

SEASONS = ["2023", "2024", "2025", "2026"]
# The 12 teams common to every season in this study, plus whichever of Northern Illinois (left for the
# Mountain West after 2025) / Sacramento St. (joined for 2026) actually played in the MAC that season.
_MAC_TEAMS_CORE = {
    "Akron", "Ball St.", "Bowling Green", "Buffalo", "Central Mich.", "Eastern Mich.", "Kent St.",
    "Massachusetts", "Miami (OH)", "Ohio", "Toledo", "Western Mich.",
}


def mac_teams_for(season):
    # Exact strings as the NCAA API's own standings endpoint spells them (confirmed directly, not
    # guessed) -- "Sacramento St.", not "Sac State".
    return _MAC_TEAMS_CORE | {"Sacramento St." if season == "2026" else "Northern Illinois"}

# Which category+position combo defines each group, and how "most productive" is scored from that
# category's raw stat fields for one season. All are real counting stats already in the pipeline's row shape.
GROUPS = {
    # rushYards/rushTd are merged in separately from the rushing leaderboard (see build() -- a passing-
    # category row has no rushing columns of its own), so a dual-threat QB's legs count toward the score
    # too, not just his arm.
    "QB": {"category": "passing", "position": "QB", "score": lambda s: s["yards"] + 25 * s["td"] - 15 * s["int"] + s["rushYards"] + 10 * s["rushTd"], "stats": ["games", "att", "yards", "td", "int", "rushYards", "rushTd"]},
    "RB": {"category": "rushing", "position": "RB", "score": lambda s: s["yards"] + 10 * s["td"], "stats": ["games", "att", "yards", "td"]},
    "WR": {"category": "receiving", "position": "WR", "score": lambda s: s["yards"] + 10 * s["td"], "stats": ["games", "rec", "yards", "td"]},
    "TE": {"category": "receiving", "position": "TE", "score": lambda s: s["yards"] + 10 * s["td"], "stats": ["games", "rec", "yards", "td"]},
    "DL": {"category": "tackling", "position": "DL", "score": lambda s: s["total"] + 2 * s["tfl"] + 6 * s["sacks"], "stats": ["games", "total", "tfl", "sacks", "pbu", "int"]},
    "LB": {"category": "tackling", "position": "LB", "score": lambda s: s["total"] + 2 * s["tfl"] + 6 * s["sacks"] + 4 * s["pbu"] + 8 * s["int"], "stats": ["games", "total", "tfl", "sacks", "pbu", "int"]},
    "CB": {"category": "tackling", "position": "CB", "score": lambda s: s["total"] + 8 * s["int"] + 4 * s["pbu"], "stats": ["games", "total", "pbu", "int"]},
    "SAF": {"category": "tackling", "position": "SAF", "score": lambda s: s["total"] + 6 * s["int"] + 3 * s["pbu"] + 1.5 * s["tfl"], "stats": ["games", "total", "tfl", "pbu", "int"]},
}
TOP_N = 10
MIN_GAMES = 4  # a game or two (missed the leaderboard cutoff most of the time) isn't "one of the best"


def num(row, key):
    try:
        return float(row.get(key, 0))
    except (TypeError, ValueError):
        return 0.0


def fetch_season(season):
    if season == REAL_STATS_SEASON:
        return fetch_season_from_real_stats()
    mac_teams = mac_teams_for(season)

    def lookup(team):
        return "MAC" if team in mac_teams else "Independent"

    rows = build_division_rows("fbs", "FBS", lookup, season=season)
    return [r for r in rows if r["conference"] == "MAC"]


def fetch_season_from_real_stats():
    """2026 pulls from the Pre-Portal Tracker's own data file instead of the NCAA leaderboard -- see the
    module docstring. Same row shape either way (player/team/category/position/games + that category's
    stat fields), so nothing downstream in build() needs to know which source a season came from."""
    with open(REAL_STATS_PATH) as f:
        all_rows = json.load(f)
    return [r for r in all_rows if r.get("division") == "FBS" and r.get("week") == "total" and r.get("conference") == "MAC"]


def build():
    by_season = {}
    for season in SEASONS:
        print(f"Fetching {season} MAC stats from {'real-stats.json' if season == REAL_STATS_SEASON else 'the NCAA API'}...")
        rows = fetch_season(season)
        by_season[season] = rows
        print(f"  {len(rows)} rows")

    study = {}
    for group_key, cfg in GROUPS.items():
        study[group_key] = {}
        for season in SEASONS:
            rows = [r for r in by_season[season] if r["category"] == cfg["category"] and r["position"] == cfg["position"]]
            # A QB's rushing line lives on a separate "rushing"-category row (same player/team) -- the
            # passing leaderboard has no rushing columns at all -- so look it up by (player, team) rather
            # than expecting it on the passing row itself.
            rushing_by_key = {}
            if group_key == "QB":
                for rr in by_season[season]:
                    if rr["category"] == "rushing":
                        rushing_by_key[(rr["player"], rr["team"])] = rr
            ranked = []
            for r in rows:
                totals = {k: num(r, k) for k in cfg["stats"]}
                if totals.get("games", 0) < MIN_GAMES:
                    continue
                if group_key == "QB":
                    rush = rushing_by_key.get((r["player"], r["team"]))
                    # A pure pocket passer legitimately has ~0 rushing yards -- unlike the DL/CB tackle gap,
                    # a QB missing from the rushing leaderboard entirely usually just means he doesn't run
                    # the ball much, so 0 here is a real value, not a leaderboard-coverage artifact.
                    totals["rushYards"] = num(rush, "yards") if rush else 0.0
                    totals["rushTd"] = num(rush, "td") if rush else 0.0
                # See _stat_overrides.py -- corrects a real gap in the leaderboard merge (a player who
                # cracked one defensive leaderboard but not "Total Tackles" specifically defaults to 0
                # there, which is never actually true for a rostered starter).
                totals.update(STAT_OVERRIDES.get((r["player"].upper(), season), {}))
                ranked.append({
                    "player": r["player"],
                    "team": r["team"],
                    "position": group_key,
                    "season": int(season),
                    "totals": totals,
                    "score": round(cfg["score"](totals), 1),
                    # Best-effort, found by hand via web search -- not exhaustive. Blank means not found
                    # yet; an admin can paste one in directly from the Studies page.
                    "hudlLink": HUDL_LINKS.get(r["player"].upper(), ""),
                    "pffLink": PFF_LINKS.get(r["player"].upper(), ""),
                    # Home state: HOME_STATES (hand-verified -- high school, not birthplace or college)
                    # wins when it has an entry; otherwise fall back to real-stats.json's own homeState
                    # for 2026 rows (it's ESPN's bio data, so birthplace rather than HS, but real and far
                    # more complete than hand-curating every week's shifting top-5 pool one player at a
                    # time). 2023-2025 rows have no "homeState" key at all, so this is a no-op for them.
                    "state": HOME_STATES.get(r["player"].upper(), "") or r.get("homeState", ""),
                })
            if group_key == "TE" and season in TE_SUPPLEMENT:
                # The leaderboard pull above still runs (kept, in case a future season has more nationally-
                # ranked MAC tight ends) but the hand-researched list is what's actually used for TE --
                # for a season that has one. 2026 doesn't yet (it's still in progress; nobody's hand-
                # researched its All-MAC-caliber TEs mid-season), so it falls through and keeps whatever
                # the real leaderboard found instead of going to zero.
                ranked = [
                    {"player": e["player"], "team": e["team"], "position": "TE", "season": int(season), "totals": e["totals"],
                     "score": round(cfg["score"](e["totals"]), 1), "hudlLink": HUDL_LINKS.get(e["player"].upper(), ""),
                     "pffLink": PFF_LINKS.get(e["player"].upper(), ""), "state": HOME_STATES.get(e["player"].upper(), "")}
                    for e in TE_SUPPLEMENT.get(season, [])
                ]
            if group_key == "CB":
                # Unlike TE, CB's leaderboard coverage is fine most seasons -- this only tops up a season
                # whose raw candidate pool came in under TOP_N (see CB_SUPPLEMENT's comment). Additive, not
                # a replacement: the real leaderboard candidates for this season stay in `ranked` too.
                for e in CB_SUPPLEMENT.get(season, []):
                    totals = {k: e["totals"].get(k, 0) for k in cfg["stats"]}
                    ranked.append({
                        "player": e["player"], "team": e["team"], "position": "CB", "season": int(season),
                        "totals": totals, "score": round(cfg["score"](totals), 1),
                        "hudlLink": HUDL_LINKS.get(e["player"].upper(), ""), "pffLink": PFF_LINKS.get(e["player"].upper(), ""),
                        "state": HOME_STATES.get(e["player"].upper(), ""),
                    })
            if group_key in ("QB", "WR"):
                # Same additive top-up as CB above, for the one season each of these came in under TOP_N.
                supplement = QB_SUPPLEMENT if group_key == "QB" else WR_SUPPLEMENT
                for e in supplement.get(season, []):
                    totals = {k: e["totals"].get(k, 0) for k in cfg["stats"]}
                    ranked.append({
                        "player": e["player"], "team": e["team"], "position": group_key, "season": int(season),
                        "totals": totals, "score": round(cfg["score"](totals), 1),
                        "hudlLink": HUDL_LINKS.get(e["player"].upper(), ""), "pffLink": PFF_LINKS.get(e["player"].upper(), ""),
                        "state": HOME_STATES.get(e["player"].upper(), ""),
                    })
            ranked.sort(key=lambda x: -x["score"])
            study[group_key][season] = ranked[:TOP_N]
            print(f"  {group_key} {season}: {len(rows)} leaderboard candidates, {len(ranked)} in the final list")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump({"generatedAt": __import__("datetime").datetime.utcnow().isoformat() + "Z", "seasons": [int(s) for s in SEASONS], "groups": study}, f, indent=2)
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    build()
